interface DisclaimerProps {
  className?: string
}

export function Disclaimer({ className = '' }: DisclaimerProps) {
  return (
    <div
      className={'p-4 bg-slate-100 dark:bg-slate-800 rounded-lg text-sm text-slate-600 dark:text-slate-400 ' + className}
    >
      <p>
        <strong>Disclaimer:</strong> This analysis is generated by AI and
        represents one interpretation of the article's content. Political
        spectrum placement is inherently subjective. Use this tool as one of
        many resources for media literacy.
      </p>
    </div>
  )
}
