import { useState } from 'react'
import { UrlInputForm } from '@/features/analysis/components/UrlInputForm'
import { AnalysisCard } from '@/features/analysis/components/AnalysisCard'
import { useAnalyzeArticle } from '@/features/analysis/hooks/useAnalyzeArticle'

function App() {
  const [url, setUrl] = useState('')
  const { mutate: analyze, data, isPending, error, reset } = useAnalyzeArticle()

  const handleAnalyze = (inputUrl: string) => {
    setUrl(inputUrl)
    analyze(inputUrl)
  }

  const handleReset = () => {
    setUrl('')
    reset()
  }

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900">
      {/* Header */}
      <header className="bg-white dark:bg-gray-800 shadow-sm">
        <div className="max-w-4xl mx-auto px-4 py-6">
          <h1 className="text-3xl font-bold text-gray-900 dark:text-white">
            Spectrum
          </h1>
          <p className="mt-1 text-gray-600 dark:text-gray-400">
            Understand where news articles fall on the political spectrum
          </p>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-4xl mx-auto px-4 py-8">
        {/* Input Form */}
        <div className="mb-8">
          <UrlInputForm
            onSubmit={handleAnalyze}
            isLoading={isPending}
            disabled={isPending}
          />
        </div>

        {/* Error State */}
        {error && (
          <div className="mb-8 p-4 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg">
            <p className="text-red-700 dark:text-red-400">
              {error instanceof Error ? error.message : 'An error occurred'}
            </p>
            <button
              onClick={handleReset}
              className="mt-2 text-sm text-red-600 dark:text-red-400 underline"
            >
              Try again
            </button>
          </div>
        )}

        {/* Loading State */}
        {isPending && (
          <div className="flex flex-col items-center justify-center py-12">
            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-violet-600"></div>
            <p className="mt-4 text-gray-600 dark:text-gray-400">
              Analyzing article...
            </p>
          </div>
        )}

        {/* Results */}
        {data?.data && !isPending && (
          <AnalysisCard analysis={data.data} />
        )}

        {/* Disclaimer */}
        <div className="mt-12 p-4 bg-gray-100 dark:bg-gray-800 rounded-lg text-sm text-gray-600 dark:text-gray-400">
          <p>
            <strong>Disclaimer:</strong> This analysis is generated by AI and represents 
            one interpretation of the article's content. Political spectrum placement is 
            inherently subjective. Use this tool as one of many resources for media literacy.
          </p>
        </div>
      </main>
    </div>
  )
}

export default App
